#!/bin/bash
#SBATCH --job-name=Pulse_Matching
#SBATCH --output=/fred/oz005/users/vdimarco/Portraiture/jobs/outputs/Pulse_Matching_%j_%a.out
#SBATCH --error=/fred/oz005/users/vdimarco/Portraiture/jobs/outputs/Pulse_Matching_%j_%a.err
#SBATCH --ntasks=1
#SBATCH --time=05:00:00
#SBATCH --tmp=4g
#SBATCH --mem-per-cpu=8g
#SBATCH --array=0

source ~/.setup_enterprise_ptasim

cd /fred/oz005/users/vdimarco/Portraiture
python PulseMatching_withDM_val.py

#python makeCommonCorner.py /fred/oz002/vdimarco/P3_spectral_index/sims/sims_for_paper/new_shuffles_$SLURM_ARRAY_TASK_ID/WN_TN_DM_CH_3/chains commonNoise_pl_nocorr_freegam_DE421/2
